### ISSUE TITLE
template_file not re-rendering on change

### ISSUE THREAD

**Issue by OJFord** [terraform-providers/terraform-provider-template#22] opened 2017-11-18 21:48 UTC
### Terraform Version
```
Terraform v0.11.0
+ provider.template v1.0.0
```

### Affected Resource(s)
- `local_file`
- `data.template_file`

### Terraform Configuration Files
```hcl
data "template_file" "docker-compose" {
  template = "${file("${path.module}/docker-compose.yml.tpl")}"

  vars {
    # ...
  }
}

resource "local_file" "docker-compose" {
  content  = "${data.template_file.docker-compose.rendered}"
  filename = "${path.root}/docker-compose.yml"

  provisioner "local-exec" {
    command =  # ...
  }
}
```

### Expected Behavior
When I modify `docker-compose.yml.tpl`, I expect `data.template_file.docker-compose` to be tainted, in turn tainting `local_file.docker-compose`.

### Actual Behavior
Even if I `terraform taint local_file.docker-compose` manually, the rendered template is cached in tfstate, and I get the same rendered file back as before. Manually modifying the `template_file` to `tainted: true` in the tfstate also has no affect; presumably because `data` sources can't be tainted (so the existence of the attribute is a bit confusing in itself).

Other than changing `local_file` for a `local-exec` provisioner that redirects the rendered output to file, (which is nasty!) the only workaround I've found is to `terraform state rm` the offending data.

### Steps to Reproduce
1. `terraform apply`
2. modify the template file
3. `terraform apply`

**Comment by apparentlymart** [comment] 2018-03-09 19:07
Hi @OJFord!

Other than manually running `terraform taint`, a resource is tainted _automatically_ only on provisioner failures. Tainting is, as you noted, not part of the data resource lifecycle, primarily because the only operation for data resources is to read them and so tainting would not have any meaning.

Reading between the lines here, I think what you want to do here is to run that `local-exec` provisioner in your `local_file` each time the file changes. Is that right?

In that case, I think this is not really a problem with the `template_file` resource so much as a limitation of Terraform Core's provisioners concept.

Provisioners only run when a resource is first created, so I can see why you went down the road of looking into tainting as a way to force Terraform to re-create that `local_file` resource. The challenge in this scenario is that the `local_file` resource is able to update `content` in-place, and so changes to that attribute do not cause the resource to be created and thus do not cause the resource to be "re-provisioned".

The provisioner concept is designed for taking actions to prepare a resource to be ready for use, rather than for implementing side-effects on changes, and so what you're doing here is a bit outside the goals of the feature. With that said, there are two different ways you could get the effect you want here:

## Separate file for each generation

This can be done within a single `resource` block by arranging for the file to "destroyed" (deleted) and re-created for each change by changing its name as well:

```hcl
resource "local_file" "docker-compose" {
  content  = "${data.template_file.docker-compose.rendered}"
  filename = "${path.root}/docker-compose-${sha1(data.template_file.docker-compose.rendered)}.yml"

  provisioner "local-exec" {
    # use self.filename in here to access the dynamically-generated filename
    command =  # ...
  }
}
```

This approach assumes that you can deal with the filename changing each time the content changes. This approach wouldn't work if that file _must_ be named `docker-compose.yml`.

## Separate `null_resource`

The `null_resource` resource type is designed to support this sort of use-case by acting as a "placeholder" resource that gets recreated each time its `triggers` change, which you can then hang provisioners on:

```hcl
resource "local_file" "docker-compose" {
  content  = "${data.template_file.docker-compose.rendered}"
  filename = "${path.root}/docker-compose.yml"
}

resource "null_resource" "docker-compose" {
  triggers = {
    config_sha1 = "${sha1(local_file.docker-compose.content)}"
  }
  provisioner "local-exec" {
    command =  # ...
  }
}
```

This separates the management of the `docker-compose.yml` file from the execution of that provisioner, but a dependency on `local_file.docker-compose` is used to ensure that the null resource is always processed after any changes to the `local_file` resource.

## Future Core Changes

I went to find the Terraform Core issue where we discussed this and was reminded that you opened that one too! In hashicorp/terraform#8099 you'd suggested `taint_on_dependency_change`, which again is conceptually not _quite_ right since "tainting" is not really the mechanism at play here, but I'd suggested renaming it to `replace_on_change` with the same effect. ("Tainted" is a state a resource can be in, while "replacing" is one of the actions we can take on a resource; resources that are tainted are always replaced on the next plan, but not all resources being replaced are tainted.)

This is still something we'd like to do eventually, but the fact that the `null_resource` workaround I mentioned above is available means it's naturally a lower priority than other features/bugs that have no available workaround. We will get to that eventually. If that feature were implemented as I sketched there then the above example might change like this:

```hcl
# Not yet implemented, and details may change before release
resource "local_file" "docker-compose" {
  content  = "${data.template_file.docker-compose.rendered}"
  filename = "${path.root}/docker-compose.yml"

  lifecycle {
    replace_on_change {
      content_sha1 = "${sha1(self.content)}"
    }
  }
}
```

**Comment by apparentlymart** [comment] 2018-03-13 22:49
The key difference here is that the `local_file` resource implements a content change as an in-place update rather than a replacement, and so provisioners don't re-run. The `null_resource` `triggers` attribute, on the other hand, is defined such that any change to it is implemented by replacing the resource, and thus the provisioners _do_ re-run.

In most situations an in-place update is preferable to a replace because replacement can cause downtime, and so most Terraform resources are implemented to do in-place updates where possible and implement update via replacement only when there's no other option. The `replace_on_change` idea would be a way to say that you actually prefer replacement for certain cases, such as this sort of situation where the replace action has a desirable side-effect.

Using the `null_resource` isn't the cause of the content changing. The content was, in fact, _always_ changing. The difference here is that the change to content _also_ causes a change to the `null_resource`, and that change is implemented via replacement rather than in-place update.

The most important thing to know about provisioners is that their goal is to perform any side-effects that make a _newly-created_ resource ready to use. This makes most sense for stateful resources like compute instances, and so provisioners as-intended don't really make sense for other resource types that are immediately ready to use after creation, but we know that many users find them convenient to use for other side-effects in situations where Terraform is missing some feature that can be implemented by running an external program.

---

In your case it sounds like the most ideal case would be for Terraform's Docker provider to have built-in support for Docker Compose, so you could manage it directly from Terraform rather than launching it as a side-effect:

```hcl
resource "docker_image" "redis" {
  name = "redis:alpine"
}

# Not currently implemented
resource "docker_compose" "example" {
  service "redis" {
    image_id = "${docker_image.redis.latest}"
  }
}
```

...though arguably this wouldn't really be any different than expressing the same thing directly with the `docker_container` resource, so maybe such a thing is not that useful. Not sure! :man_shrugging: But if that sounds interesting perhaps we could discuss it more in [the docker provider's own repository](https://github.com/terraform-providers/terraform-provider-docker).

**Comment by ROunofF** [comment] 2018-05-11 18:14
Found this issue because I had template_file not re-rendered after changing the external file. It looks like that if you run with "-refresh=false" it won't see your changes over that "template_file". If you leave the refresh mode on (default) it will see any modifications and apply them correctly!

It looks like the hash is only compute on "refresh"

Not really linked to the OP but I think this deserve a note over this issue since it may lead other people to the same post.

**Comment by DanielChuDC** [comment] 2019-11-08 03:43
Hi, any update on this? Currently I am using @apparentlymart 's solution to force trigger the build every time I change the file.

**Comment by apparentlymart** [comment] 2019-11-08 17:35
Hi all!

Re-reading this issue I see that, as I'd noted above, the problem being described here isn't really anything to do with the template provider or the `template_file` data source... it's really a feature request for that `replace_on_change` feature I was discussing in an earlier comment. Since that feature was already discussed in hashicorp/terraform#8099 I'm going to close this one just to consolidate the discussion.

**Closed by apparentlymart** 2019-11-08 17:35 UTC
Labels: bug
